apiVersion: v1
kind: Pod
metadata:
  name: po-1
spec:
  schedulerName: doslab-gpu-scheduler
  containers:
  - image: pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
    name: torch
    command: [ "sh", "-c", "python3 /workspace/pytorch-cifar/main.py" ]
    resources:
      limits:
        doslab.io/gpu-memory: 2288
        doslab.io/gpu-core: 40
    volumeMounts:
    - mountPath: /workspace
      name: code
  volumes:
  - name: code
    hostPath:
      path: /root/gpushare/code
      type: Directory
