---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gpus.doslab.io
spec:
  group: doslab.io
  names:
    kind: GPU
    listKind: GPUList
    plural: gpus
    singular: gpu
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - jsonPath: .spec.node
          name: node
          type: string
        - jsonPath: .spec.model
          name: model
          type: string
        - jsonPath: .status.allocated.core
          name: core used
          type: string
        - jsonPath: .status.allocated.memory
          name: memory used
          type: string
        - jsonPath: .spec.capacity.memory
          name: memory capacity
          type: string
